# Use Trusty for a C++11 compiler, for our native dependencies:
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Node.js-v4-(or-io.js-v3)-compiler-requirements
dist: trusty
# Containers for faster startup, also we don't need sudo.
sudo: false

language: node_js
node_js: 6.9.1

cache: yarn

env:
  global:
    - DISPLAY=:99.0

before_script:
  # update npm
  - npm install -g npm
  - npx selenium-standalone install
  - 'sh -e /etc/init.d/xvfb start'
  - sleep 3 # give xvfb some time to start
  - npx selenium-standalone start &

script: 'yarn ci'
