# Use Trusty for a C++11 compiler, for our native dependencies:
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Node.js-v4-(or-io.js-v3)-compiler-requirements
dist: trusty
# Containers for faster startup, also we don't need sudo.
sudo: false

addons:
  sauce_connect: true

language: node_js
node_js: 6.9.1

cache: yarn

script: 'yarn ci'
